# Generated by Django 5.1.7 on 2025-03-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descriptions',
            field=models.TextField(default='Описание элемента', max_length=200),
        ),
    ]
